idf_component_register(SRC_DIRS .
                        INCLUDE_DIRS "include"
                        PRIV_REQUIRES 
                            toolbox   
                            wifi_service 
                            setting_server 
                            device_common 
                            forecast 
                            sound_generator 
                            adc_reader 
                            driver 
                            epaper_adapter 
                            clock_module 
                            esp_timer 
                            display_icons
                    ) 